// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AddRepositoryResult is what the frontend gets back from a single click of the
 * plus button. It always carries the resulting Workspace so the UI can replace its
 * state from one call, plus enough detail to explain what happened.
 */
export interface AddRepositoryResult {
    "workspace": Workspace;

    /**
     * Repo is the repository that was added or, when Duplicate is set, the
     * existing entry that is now selected. It is nil if the user cancelled.
     */
    "repo": Repo | null;

    /**
     * Cancelled reports that the user dismissed the folder picker.
     */
    "cancelled": boolean;

    /**
     * Duplicate reports that the chosen folder was already in the workspace.
     */
    "duplicate": boolean;
}

/**
 * Branch is a single local branch and its merge status, read live from the
 * repository — never persisted.
 */
export interface Branch {
    "name": string;
    "head": string;
    "isCurrent": boolean;
    "committerDate": string;

    /**
     * MergedToHead reports that this branch's tip is an ancestor of HEAD, i.e.
     * it has already been merged.
     */
    "mergedToHead": boolean;
}

/**
 * BranchInfo is a repository's local branches and the merge edges between them,
 * read live — never persisted.
 */
export interface BranchInfo {
    "branches": Branch[] | null;
    "merges": MergeEdge[] | null;
}

/**
 * MergeEdge is one merge commit found by walking a branch's first-parent chain:
 * Into received the merge. From is the branch whose tip was merged in, filled in
 * only when the merged-in commit exactly matches a currently existing local
 * branch's tip — if that branch has since been deleted, From is "" rather than a
 * guess (see AGENTS.md: never silently guess wrong about topology).
 */
export interface MergeEdge {
    "into": string;
    "from": string;
    "commit": string;
    "when": string;
}

/**
 * Repo is a single Git repository the user has added to the workspace.
 */
export interface Repo {
    /**
     * ID is derived from Path and is stable across restarts, so the frontend can
     * use it as a key and to address a repo in service calls.
     */
    "id": string;

    /**
     * Name is the display label — the repository folder's name.
     */
    "name": string;

    /**
     * Path is the absolute path to the root of the working tree (or to the
     * repository itself, if bare).
     */
    "path": string;
    "addedAt": string;

    /**
     * Missing reports that Path could not be found on disk. It is recomputed on
     * every read, so the value persisted alongside the rest is never trusted: an
     * unplugged drive or an unmounted share should grey a repo out, not silently
     * drop it from the workspace.
     */
    "missing": boolean;
}

/**
 * Workspace is the whole persisted state: the repositories the user has added,
 * and which one is currently selected.
 */
export interface Workspace {
    "version": number;
    "repos": Repo[] | null;
    "activeId": string;
}
