// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AddRepositoryResult is what the frontend gets back from a single click of the
 * plus button. It always carries the resulting Workspace so the UI can replace its
 * state from one call, plus enough detail to explain what happened.
 */
export interface AddRepositoryResult {
    "workspace": Workspace;

    /**
     * Repo is the repository that was added or, when Duplicate is set, the
     * existing entry that is now selected. It is nil if the user cancelled.
     */
    "repo": Repo | null;

    /**
     * Cancelled reports that the user dismissed the folder picker.
     */
    "cancelled": boolean;

    /**
     * Duplicate reports that the chosen folder was already in the workspace.
     */
    "duplicate": boolean;
}

/**
 * Branch is a single branch on the "origin" remote and its merge status, read
 * live from the repository's local refs/remotes/origin/* cache — never
 * persisted. Names have the "origin/" prefix stripped (e.g. "main", not
 * "origin/main").
 */
export interface Branch {
    "name": string;
    "head": string;
    "committerDate": string;

    /**
     * IsCurrent reports that this is the upstream of the repository's currently
     * checked-out local branch (by name — not a strict tracking-ref check).
     * False, rather than a guess, when HEAD is detached or has no same-named
     * origin branch.
     */
    "isCurrent": boolean;

    /**
     * IsDefault reports that this is origin's default branch, resolved from the
     * refs/remotes/origin/HEAD symref. That symref isn't always present (e.g. a
     * manually added remote), in which case no branch is marked default.
     */
    "isDefault": boolean;

    /**
     * MergedToDefault reports that this branch's tip is an ancestor of origin's
     * default branch, i.e. it has already been merged there. Always false when
     * IsDefault couldn't be resolved for any branch.
     */
    "mergedToDefault": boolean;
}

/**
 * BranchInfo is a repository's origin branches and the merge edges between
 * them, read live from refs/remotes/origin/* — never persisted, never fetched.
 */
export interface BranchInfo {
    "branches": Branch[] | null;
    "merges": MergeEdge[] | null;
}

/**
 * MergeEdge is one merge commit found by walking an origin branch's
 * first-parent chain: Into received the merge. From is the origin branch whose
 * tip was merged in, filled in only when the merged-in commit exactly matches
 * another current origin branch's tip — if that branch has since been deleted
 * on the server, From is "" rather than a guess (see AGENTS.md: never silently
 * guess wrong about topology).
 */
export interface MergeEdge {
    "into": string;
    "from": string;
    "commit": string;
    "when": string;
}

/**
 * Repo is a single Git repository the user has added to the workspace.
 */
export interface Repo {
    /**
     * ID is derived from Path and is stable across restarts, so the frontend can
     * use it as a key and to address a repo in service calls.
     */
    "id": string;

    /**
     * Name is the display label — the repository folder's name.
     */
    "name": string;

    /**
     * Path is the absolute path to the root of the working tree (or to the
     * repository itself, if bare).
     */
    "path": string;
    "addedAt": string;

    /**
     * Missing reports that Path could not be found on disk. It is recomputed on
     * every read, so the value persisted alongside the rest is never trusted: an
     * unplugged drive or an unmounted share should grey a repo out, not silently
     * drop it from the workspace.
     */
    "missing": boolean;
}

/**
 * Workspace is the whole persisted state: the repositories the user has added,
 * and which one is currently selected.
 */
export interface Workspace {
    "version": number;
    "repos": Repo[] | null;
    "activeId": string;
}
