// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WorkspaceService owns the set of repositories the user is working with and the
 * JSON file they are persisted to. It is the frontend's only route to that state.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddRepository opens a native folder picker and adds the chosen directory. If the
 * user picks a subdirectory of a repository, the repository root is added.
 */
export function AddRepository(): $CancellablePromise<$models.AddRepositoryResult> {
    return $Call.ByID(2745359231);
}

/**
 * GetBranches reads repo id's origin branches and merge topology from whatever
 * refs/remotes/origin/* already holds locally.
 */
export function GetBranches(id: string): $CancellablePromise<$models.BranchInfo> {
    return $Call.ByID(1836375704, id);
}

/**
 * GetWorkspace returns the current repositories and selection. Called once when
 * the UI mounts.
 */
export function GetWorkspace(): $CancellablePromise<$models.Workspace> {
    return $Call.ByID(1704256705);
}

/**
 * RemoveRepository forgets a repository. Nothing on disk is touched — only this
 * app's list of what to show.
 */
export function RemoveRepository(id: string): $CancellablePromise<$models.Workspace> {
    return $Call.ByID(3665824196, id);
}

/**
 * SetActiveRepository records which tab is selected, so the same one is open on
 * the next launch.
 */
export function SetActiveRepository(id: string): $CancellablePromise<$models.Workspace> {
    return $Call.ByID(240552514, id);
}

/**
 * SetLaneOrder saves repo id's lane order — the branch names, top to bottom,
 * the user dragged into place. Names not among the repo's current branches
 * are harmless (GetBranches's reconciliation drops them on the next read),
 * so no validation against live branches happens here.
 */
export function SetLaneOrder(id: string, order: string[] | null): $CancellablePromise<$models.Workspace> {
    return $Call.ByID(1052165778, id, order);
}
